# fly.toml app configuration file generated for one-sport on 2023-08-12T15:50:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "one-sport"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_DEBUG = "true"
  APP_ENV = "production"
  APP_URL = "https://one-sport.fly.dev"
  AWS_BUCKET = "onesport-storage"
  AWS_DEFAULT_REGION = "eu-north-1"
  AWS_USE_PATH_STYLE_ENDPOINT = "false"
  BROADCAST_DRIVER = "log"
  CACHE_DRIVER = "redis"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "one-sport"
  DB_HOST = "aws.connect.psdb.cloud"
  DB_PORT = "3306"
  FILESYSTEM_DISK = "local"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAIL_ENCRYPTION = "tls"
  MAIL_FROM_ADDRESS = "yanush.polishchuk@gmail.com"
  MAIL_FROM_NAME = "OneSport"
  MAIL_HOST = "smtp.gmail.com"
  MAIL_MAILER = "smtp"
  MAIL_PORT = "587"
  MEMCACHED_HOST = "memcached"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"
  PAYPAL_TEST_MODE = "true"
  QUEUE_CONNECTION = "sync"
  REDIS_URL = "redis://default:a9bdb01bdf8f4625b7a231bfd99bdd0f@fly-solitary-thunder-8205.upstash.io"
  SESSION_DRIVER = "database"
  SESSION_LIFETIME = "120"
  GOOGLE_REDIRECT_URI = "https://one-sport.fly.dev/login/google/callback"
  FACEBOOK_REDIRECT_URI = "https://one-sport.fly.dev/login/facebook/callback"

[[mounts]]
  source = "storage_vol"
  destination = "/var/www/html/storage"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
